### PR TITLE
docs: add vscode cheatsheet

### PR DESCRIPTION
**Pull request by loctran016**
I'll try my best to finish this

### CODE REVIEW

**Comment by Randy8080** [comment]
Are you kidding me?😃 This is just an empty file！

**Comment by Randy8080** [comment]
Are you kidding me😃? This is just an empty file！

Actually, you can refer to a chestsheet, such as [vim cheatsheet](https://github.com/Randy8080/reference/blob/main/vim.md), I believe that you can get inspiration from this file! If you have any questions, please feel free to ask me!

Thanks for your contributing!

**Comment by loctran016** [comment]
I'm working on it on my local machine, I try to push it soon

**Comment by Randy8080** [comment]
Hi  loctran016, 

It would be great if this VSCode cheat sheet contains some commonly used shortcut keys, plugins, And some general configuration examples.

Thank you for your work!

**Pull request closed without merging**
